### ISSUE TITLE
SftpClient + keyboard-interactive authentication.

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok#832]
# Summary

If the remote SFTP server is configured to not allow `password` as an authentication method, then there is no way for Interlok to connect via SFTP using a password via `sftp-password-authentication`.  It's possible to connect using a keys if you use `sftp-key-authentication`

It's difficult to tell from the JSch source code precisely what's happening, but I think we iterate over the PreferredAuthentications we try to match up against what the server is offering us. If there's a match and we are configured to use it then we try it. Once we are exhausted, and we are not successful then we through the `Auth Fail` exception.

The challenge here is really "setting up a server" that doesn't allow `password` authentication so that you can test it (I haven't investigated how to configure OpenSSH Server to do that, since `PasswordAuthentication no` means use _publickey_ and yes presumably means both password+keyboard-interactive since we test against openssh)

## Interlok logging

This was the initial log extract; since we know that SFTP hasn't *changed* since probably about 3.6 we can safely say that "upgrade to see if this fixes the issue" isn't the right statement.

```
adapter_1  | ERROR [ctn-sftp-getter] [FtpConsumer] Failed to connect to [XXXX]
adapter_1  | com.adaptris.sftp.SftpException: com.jcraft.jsch.JSchException: Auth fail
adapter_1  |    at com.adaptris.sftp.SftpClient.connect(SftpClient.java:221) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.sftp.SftpClient.connect(SftpClient.java:176) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.ftp.SftpPasswordAuthentication.connect(SftpPasswordAuthentication.java:57) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.ftp.StandardSftpConnection.create(StandardSftpConnection.java:98) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.ftp.FileTransferConnection.create(FileTransferConnection.java:290) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.ftp.FileTransferConnection.connect(FileTransferConnection.java:269) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.ftp.FtpConsumerImpl.processMessages(FtpConsumerImpl.java:105) [interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.PollerImp.processMessages(PollerImp.java:74) [interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at com.adaptris.core.QuartzCronPoller$MyProcessJob.execute(QuartzCronPoller.java:447) [interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz.jar!/:?]
adapter_1  |    at 
...
adapter_1  | Caused by: com.jcraft.jsch.JSchException: Auth fail
adapter_1  |    at com.jcraft.jsch.Session.connect(Session.java:519) ~[jsch.jar!/:?]
adapter_1  |    at com.adaptris.sftp.SftpClient.connect(SftpClient.java:213) ~[interlok-core.jar!/:3.9.1-RELEASE]
adapter_1  |    ... 12 more
```

## Test Class

- In this test class `StdErrLogger` is just a Jsch.Logger implementation that dumps everything to std error.
- BasicUserInfo is directly copied from `StandardUserInfo` from the SftpClient class in Interlok
- (1) is effectively what Interlok does
- (2) according to the code, you must call setPassword() and NOT have a UserInfo  (Check UserAuthKeyboardInteractive class in JSch).

```java
  private static final int DEFAULT_TIMEOUT = 1000 * 60;
  public static final String PREF_AUTH =  "publickey,keyboard-interactive,password";
  public static final String SSH_PREFERRED_AUTHENTICATIONS = "PreferredAuthentications";

  public static void main(String[] argv) throws Exception {

    String sshHost = System.getenv("SFTP_HOST");
    int sshPort = Integer.parseInt(System.getenv("SFTP_PORT"));
    String user = System.getenv("SFTP_USER");
    String password = Password.decode(System.getenv("SFTP_PASSWORD"));
    Session sftpSession = null;
    ChannelSftp sftpChannel = null;
    JSch.setLogger(new StdErrLogger());
    try {
      JSch jsch = new JSch();
      sftpSession = jsch.getSession(user, sshHost, sshPort);
      sftpSession.setConfig(SSH_PREFERRED_AUTHENTICATIONS, PREF_AUTH);
      sftpSession.setConfig("StrictHostKeyChecking", "no");
      // Switch to keyboard-interactive, using setUserInfo implies 'password' under the covers.
      // ------------ (1)
      // sftpSession.setUserInfo(new BasicUserInfo(password));
      // ------------ (2)
      // This should switch to keyboard-interactive.
      sftpSession.setPassword(password);
      log(String.format("Connect (SSH) : %s, user=[%s] password=[%s]", sshHost, user, password));
      // expect it to fail here.
      sftpSession.connect(DEFAULT_TIMEOUT);
      Channel c = sftpSession.openChannel("sftp");
      c.connect(DEFAULT_TIMEOUT);
      sftpChannel = (ChannelSftp) c;
    } finally {
      sftpChannel.disconnect();
      sftpSession.disconnect();
    }
  }
```

If we use (1) then our logging shows this (i.e. this is standard Interlok behaviour).

Now you'd think that the logging indicates that we _haven't tried_ password; but you need to step through the JschSession code, because the trace logging isn't that *good*. We try `keyboard-interactive` (but it's not deemed appropriate by Jsch because of our session setup); then we __skip__ password entirely, and fail with the `Auth Fail`

```
adapter_1  | kex: host key algorithm: ssh-ed25519
adapter_1  | kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
adapter_1  | kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
adapter_1  | SSH_MSG_KEX_ECDH_INIT sent
adapter_1  | expecting SSH_MSG_KEX_ECDH_REPLY
adapter_1  | ssh_eddsa_verify: ssh-ed25519 signature true
adapter_1  | SSH_MSG_NEWKEYS sent
adapter_1  | SSH_MSG_NEWKEYS received
adapter_1  | SSH_MSG_SERVICE_REQUEST sent
adapter_1  | SSH_MSG_EXT_INFO received
adapter_1  | server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
adapter_1  | OpenSSH 7.4 detected: adding rsa-sha2-256 & rsa-sha2-512 to server-sig-algs
adapter_1  | SSH_MSG_SERVICE_ACCEPT received
adapter_1  | Authentications that can continue: publickey,keyboard-interactive,password
adapter_1  | Next authentication method: publickey
adapter_1  | Authentications that can continue: keyboard-interactive,password
adapter_1  | Next authentication method: keyboard-interactive
adapter_1  | Disconnecting from XXXXXXXX port 22
adapter_1  | Exception in thread "main" com.jcraft.jsch.JSchException: Auth fail
adapter_1  |    at com.jcraft.jsch.Session.connect(Session.java:524)
adapter_1  |    at io.github.quotidianennui.TestSftpConnect.main(TestSftpConnect.java:45)
exited with code 0
```

If we use (2) then our logging shows this:

```
adapter_1  | kex: algorithm: curve25519-sha256
adapter_1  | kex: host key algorithm: ssh-ed25519
adapter_1  | kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
adapter_1  | kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
adapter_1  | SSH_MSG_KEX_ECDH_INIT sent
adapter_1  | expecting SSH_MSG_KEX_ECDH_REPLY
adapter_1  | ssh_eddsa_verify: ssh-ed25519 signature true
adapter_1  | SSH_MSG_NEWKEYS sent
adapter_1  | SSH_MSG_NEWKEYS received
adapter_1  | SSH_MSG_SERVICE_REQUEST sent
adapter_1  | SSH_MSG_EXT_INFO received
adapter_1  | server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
adapter_1  | OpenSSH 7.4 detected: adding rsa-sha2-256 & rsa-sha2-512 to server-sig-algs
adapter_1  | SSH_MSG_SERVICE_ACCEPT received
adapter_1  | Authentications that can continue: publickey,keyboard-interactive,password
adapter_1  | Next authentication method: publickey
adapter_1  | Authentications that can continue: keyboard-interactive,password
adapter_1  | Next authentication method: keyboard-interactive
adapter_1  | Authentication succeeded (keyboard-interactive).
adapter_1  | Disconnecting from XXXXX port 22
adapter_1  | Caught an exception, leaving main loop due to Socket closed
```

## Options

Not entirely sure what the appropriate course of action is. On the face of it we can do this.

- Make SftpClient a base class (with protected members)
    - Make a KeyboardInteractiveSftpClient that does (2)
    - How do we make SftpConnection *choose* which version to use?

- Make SftpClient try/catch a password attempt, and if that fails, try/catch a keyboard-interactive attempt which means re-creating the session ?

**Comment by quotidian-ennui** [comment]
Apparently you can configure sshd_config something like this (this would give us publickey,keyboard-interactive as valid auth methods) -> ChallengeResponseAuth is often explicitly configured as "no".

```
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication yes
PasswordAuthentication no
```

Which, if you do a `ssh -vvv host` then you get 

```
debug3: input_userauth_banner
Access is granted to this server to authorized personnel only
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,keyboard-interactive
debug3: start over, passed a different list publickey,keyboard-interactive
debug3: preferred publickey,keyboard-interactive
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/vagrant/.ssh/id_rsa
debug3: no such identity: /home/vagrant/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/vagrant/.ssh/id_dsa
debug3: no such identity: /home/vagrant/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/vagrant/.ssh/id_ecdsa
debug3: no such identity: /home/vagrant/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/vagrant/.ssh/id_ed25519
debug3: no such identity: /home/vagrant/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /home/vagrant/.ssh/id_xmss
debug3: no such identity: /home/vagrant/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred:
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 60
debug2: input_userauth_info_req
debug2: input_userauth_info_req: num_prompts 1
Password:  // we type are password in at this point.
debug3: send packet: type 61
debug3: receive packet: type 60
debug2: input_userauth_info_req
debug2: input_userauth_info_req: num_prompts 0
debug3: send packet: type 61
debug3: receive packet: type 52
debug1: Authentication succeeded (keyboard-interactive).
```
